services:
  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=miniprojet
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: start-dev
    networks:
      - app-network

  discovery-service:
    container_name: eureka
    build: ./eureka
    ports:
      - "8761:8761"
    image: "eureka"
    environment:
      - eureka.client.server-url.default-zone=http://discovery-service:8761/eureka/
    networks:
      - app-network

  forum-service:
    container_name: forum-service
    build: ./forum
    ports:
      - "8055:8055"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - app-network

  publication-service:
    container_name: publication-service
    build: ./Publication
    ports:
      - "8056:8056"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - app-network

  activities-service:
    container_name: activities-service
    build: ./Activities
    ports:
      - "8058:8058"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - app-network

  gateway:
    container_name: Gateway
    image: "gateway"
    build: ./Gateway
    ports:
      - "8094:8094"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
    restart: unless-stopped
    depends_on:
      - discovery-service
    networks:
      - app-network

  apigateway:
    container_name: Api_Gateway_Server
    image: "apigatewayms"
    build: ./GatewayApi
    ports:
      - "8093:8093"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - SPRING_MAIN_WEB_APPLICATION_TYPE=reactive
    restart: unless-stopped
    depends_on:
      - discovery-service
      - db-mysql
      - keycloak
    networks:
      - app-network

  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - "27017:27017"
    command: mongod --port 27017
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  reclamation:
    container_name: reclamation
    build: ./reclamation_nodejs
    ports:
      - "8500:8500"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/microservice
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/  # Correction ici
    depends_on:
      - discovery-service
      - mongodb
    networks:
      - app-network



# Ajout du réseau commun
networks:
  app-network:
    driver: bridge

# Définition du volume pour MongoDB
volumes:
  mongodb-data: