version: "2.2"
services:
  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=miniprojet
    ports:
      - "3306:3306"
    restart: unless-stopped

  discovery-service:
    container_name: eureka
    build: ./eureka
    ports:
      - "8761:8761"
    image: "eureka"
    environment:
      - eureka.client.server-url.default-zone=http://discovery-service:8761/eureka/

  candidat-service:
    container_name: candidat-service
    build: ./candidat
    ports:
      - "8082:8082"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service


  forum-service:
    container_name: forum-service
    build: ./forum
    ports:
      - "8055:8055"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service

  apigateway:
     container_name: Api_Gateway_Server
     image: "apigatewayms"
     build: ./GatewayApi
     ports:
      - "8089:8089"
     environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
     restart: unless-stopped
     depends_on:
      - discovery-service
      - db-mysql